DROP DATABASE IF EXISTS `CalendarDB`;
CREATE DATABASE IF NOT EXISTS `CalendarDB`;
USE `CalendarDB`;

DROP TABLE IF EXISTS `Users`;
DROP TABLE IF EXISTS `Groups`;
DROP TABLE IF EXISTS `GroupUsers`;

CREATE TABLE `Users` (
  `UserID` INTEGER NOT NULL AUTO_INCREMENT, 
  `UserName` VARCHAR(50) UNIQUE NOT NULL,
  `Email` VARCHAR(100) NOT NULL, 
  `Password` VARCHAR(255) NOT NULL,
  `Affiliation` VARCHAR(100), 
  INDEX (`UserID`), 
  INDEX (`UserName`), 
  PRIMARY KEY (`UserName`)
) ENGINE=innodb DEFAULT CHARSET=utf8;

SET autocommit=1;

CREATE TABLE `Groups` (
	`GroupID` INT NOT NULL AUTO_INCREMENT,
	`AdminID` INT NOT NULL,
    `GroupName` VARCHAR(50) UNIQUE NOT NULL,
    `Password` VARCHAR(255) NOT NULL,
	`StartDate` DATETIME NOT NULL,
	`EndDate` DATETIME NOT NULL,
	PRIMARY KEY (`GroupID`)
) ENGINE=innodb DEFAULT CHARSET=utf8;

CREATE TABLE `GroupUsers` (
	`GroupID` INT NOT NULL,
	`UserID` INT NOT NULL,
	PRIMARY KEY (`GroupID`,`UserID`)
) ENGINE=innodb DEFAULT CHARSET=utf8;

ALTER TABLE `Groups` ADD CONSTRAINT `Groups_fk0` FOREIGN KEY (`AdminID`) REFERENCES `Users`(`UserID`);

ALTER TABLE `GroupUsers` ADD CONSTRAINT `GroupUsers_fk0` FOREIGN KEY (`GroupID`) REFERENCES `Groups`(`GroupID`);

ALTER TABLE `GroupUsers` ADD CONSTRAINT `GroupUsers_fk1` FOREIGN KEY (`UserID`) REFERENCES `Users`(`UserID`);

